version: "3.9"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
